08-interactions-and-logic-reuse
js-tasks-ru/vue-20200925-2_oleg-bolshakov pull request #11
Opened 2021-05-09 14:23 UTC by BolshakovOleg

All the tasks are done

2021-05-09 14:23 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-05-11 14:46 UTC, ShGKme requested changes
`CalendarView` требуется сделать более универсальным календарём, не связанным с митапами, остальные задачи приняты.

2021-05-11 14:46 UTC, ShGKme commented on 08-interactions-and-logic-reuse/03-CalendarView/components/CalendarView.vue
> +  },
Если компонент `CalendarView` принимает на вход список митапов, то и использоваться он может только как календарь отображения митапов. Здесь слот позволяет изменить содержимое ячейки, но календарь остался календарём митапов и не может использоваться для отображения других данных, например, отображения запланированных задач, дней рождений пользователей и т.д.

Кроме того, данные могут быть представленный разной структурой. В отличии от предыдущих двух задач со слотами, где данные просто выводились, как есть, здесь нужно знать, где в них дата и в каком виде.

Чтобы компонент был более универсальным, он может предоставлять слот для рендеринга одной ячейки, и в слот передавать только дату в том или ином виде. Уже родительский компонент будет по дате определять, какое именно содержимое с какими данными должно рендериться в конкретной ячейке.

2021-05-11 14:46 UTC, ShGKme commented on 08-interactions-and-logic-reuse/03-CalendarView/components/CalendarView.vue
> +    },
Да, для упрощения задачи считаем, что начинаем с понедельника. С названием месяца проще, его в основных браузерах в любом случае просто брать из модуля интернационализации.

В тоже время широко поддерживаемого API в браузере для определения первого дня недели пока нет. Сейчас на Stage 3: https://github.com/tc39/proposal-intl-locale-info, на практике используются разные сторонние библиотеки.

2021-05-11 14:46 UTC, ShGKme commented on 08-interactions-and-logic-reuse/05-TopProgressBarPlugin/plugins/TopProgressBar/plugin.js
> +    const instance = new ComponentClass();
Аналогично работает `new Vue(TheTopProgressBar);`

2021-05-14 12:39 UTC, ShGKme approved these changes
Все задачи приняты.

В `CalendarView` есть не очень хорошее место, но основная часть задачи в разработке компонента со слотом - решена. Это место можно будет поправить, если будете решать задачу `RenderlessCalendar`, где требуются такие же компоненты.

2021-05-14 12:39 UTC, ShGKme commented on 08-interactions-and-logic-reuse/03-CalendarView/components/MeetupsCalendar.vue
> +      v-for="meetup in getMeetupsByDate(date)"
Это не очень оптимальное решение и Vue-way. Каждый раз при каждом ререндеринге для каждой ячейки будет вызываться метод, который ищет нужные митапы для каждого дня заново.

Чтобы этого избежать можно сразу привести данные к наиболее удобной структуре, например, объекту, где ключ - это дата, а значение - список митапов этого дня. Тогда получить митапы в шаблоне можно будет просто по `meetup in meetupsByDay[date]`. Подготовить такую структуру можно в вычисляемом свойстве.

2021-05-14 12:41 UTC, merged